---
title: 'Causal Inference #4'
author: 'Javier Esteban Aragoneses, Mauricio Marcos Fajgenbaun, Danyu Zhang, Daniel Alonso'
date: 'March 20, 2021'
output: 'pdf_document'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
collapse = TRUE,
comment = '#>',
fig.path = './figures/'
)
knitr::knit_engines$set(julia = JuliaCall::eng_juliacall)
options(JULIA_HOME = '/home/dreth/julia/bin')
```

# Introduction

For our project, We will be using the Memory Test on Drugged Islanders data set, 

for more information, click [link]()

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# importing libraries
pkgs <- c("glmnet", "rpart", "rpart.plot", "randomForest", "devtools", "tidyverse", "knitr", "caret", "xgboost", "causalTree","grf", "fastDummies", "stringr", 'caret')
invisible(lapply(pkgs, library, character.only = TRUE))
```

# Model

```{r, echo=TRUE, warning=FALSE, message=FALSE}
# importing data
df <- read.csv('./data/heartdata.csv', sep=',')
df <- df[c("anaemia","diabetes","high_blood_pressure","smoking","DEATH_EVENT","platelets")]
```

```{r, echo=TRUE, warning=FALSE, message=FALSE}
# importing data
df <- read.csv('./data/Islander_data.csv', sep=',')
df <- df[c("age","Happy_Sad_group","Dosage","Drug","Diff")]
df$Happy_Sad_group <- as.numeric(ifelse(df$Happy_Sad_group == 'H', 1, 0))
df <- df %>% dplyr::filter(Drug != 'T')
df$Drug <- as.numeric(ifelse(df$Drug == 'A', 1, 0))
df$Dosage <- as.numeric(df$Dosage)
```

```{r, echo=TRUE, warning=FALSE, message=FALSE}
# Random forest to find most important variable
form <- as.formula(str_interp("Diff~${paste(names(df)[names(df)!='Diff'], collapse='+')}"))
rf <- randomForest(form,data=df ,importance=TRUE ,mtry=3 ,ntree=1000)
varImpPlot(rf, main="Variable importance")
```

# Causal forest

```{r, echo=TRUE, warning=FALSE, message=FALSE}
# full dataset
X = df[names(df) != 'Diff' & names(df) != 'Drug']
Y = df[,"Diff"]
W = df[,"Drug"]

# causal forests
cf = causal_forest(X,Y,W,num.trees=1000)

# Estimate treatment effects for the training data using out-of-bag prediction.
preds = predict(cf)
hist(preds$predictions)
```

```{r, echo=TRUE, warning=FALSE, message=FALSE}
# Estimate the conditional average treatment effect on the full sample (CATE).
average_treatment_effect(cf, target.sample = "all")
```

```{r, echo=TRUE, warning=FALSE, message=FALSE}
# Estimate the conditional average treatment effect on the treated sample (CATT).
# Here, we don't expect much difference between the CATE and the CATT, since
# treatment assignment was randomized.
average_treatment_effect(cf, target.sample = "treated")
```

```{r, echo=TRUE, warning=FALSE, message=FALSE}
# Add confidence intervals for heterogeneous treatment effects; growing more
# trees is now recommended.
cf = causal_forest(X, Y, W, num.trees = 4000)
sd(cf$predictions)
```